apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-known-halibut
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "579564047599"
    project: testkube-345804
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: synectiks-sddc
    repository: jx3-gke-vault
  - key: staging
  - key: production
  ingress:
    domain: 104.198.220.144.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: synectiks-code
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-tf-jx-known-halibut-5a204bc0b625
  - name: reports
    url: gs://reports-tf-jx-known-halibut-5a204bc0b625
  - name: repository
    url: gs://repository-tf-jx-known-halibut-5a204bc0b625
  vault: {}
  webhook: lighthouse
