apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-current-ewe
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "579564047599"
    project: testkube-345804
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: synectiks-sddc
    repository: jx3-gke-vault
  - key: staging
  - key: production
  ingress:
    domain: 34.132.76.48.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: synectiks-code
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: gs://logs-tf-jx-current-ewe-303f6489b4a3
  - name: reports
    url: gs://reports-tf-jx-current-ewe-303f6489b4a3
  - name: repository
    url: gs://repository-tf-jx-current-ewe-303f6489b4a3
  terraformVault: true
  vault:
    bucket: vault-tf-jx-current-ewe-303f6489b4a3
    key: crypto-key-tf-jx-current-ewe-303f6489b4a3
    keyring: keyring-tf-jx-current-ewe-303f6489b4a3
    name: tf-jx-current-ewe
    serviceAccount: tf-jx-current-ewe-vt
  webhook: lighthouse
